name: Deploy API to Render with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create terraform.tfvars
        run: |
          cat > terraform.tfvars <<EOF
          RENDER_API_KEY = "${{ secrets.RENDER_API_KEY }}"
          RENDER_OWNER_ID = "${{ secrets.RENDER_OWNER_ID }}"
          DATABASE_URL = "${{ secrets.DATABASE_URL }}"
          HOST = "${{ secrets.HOST }}"
          JWT_SECRET_KEY = "${{ secrets.JWT_SECRET_KEY }}"
          COOKIE_SECRET = "${{ secrets.COOKIE_SECRET }}"
          GOOGLE_CLIENT_ID = "${{ secrets.GOOGLE_CLIENT_ID }}"
          GOOGLE_CLIENT_SECRET = "${{ secrets.GOOGLE_CLIENT_SECRET }}"
          AWS_BUCKET_NAME = "${{ secrets.AWS_BUCKET_NAME }}"
          AWS_ACCESS_KEY_ID = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import
        run: terraform import render_web_service.mon-vieux-grimoire-api srv-crklp508fa8c738gmamg

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve

      - name: Clean up tfvars
        run: rm -f terraform.tfvars
